version: "3.1"
services:
   db:
     image: mysql:5.7
     container_name: tourism-bd
     working_dir: :/go/src/github.com/laurabcn/gobcn
     volumes:
       - ./docker/data/mysql:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=tourist
       - MYSQL_USER=root
       - MYSQL_PASSWORD=root
     ports:
       - "8082:3306"
   gorker:
      container_name: gorker
      environment:
          ENVIRONMENT_GORKER: docker
      build:
        dockerfile: ./docker/golang/Dockerfile
      image: gorker
      volumes:
        - .:/go/src/github.com/laurabcn/gobcn
      depends_on:
        - db
