version: "3.1"
services:
  app:
       image: golang
       volumes:
          - .:/go/src/go-with-compose
       ports:
          - "8080:8080"
       working_dir: /go/src/awesomeProject2
       links:
         - db
  db:
        image: mysql:5.7
        container_name: tourism-bd
        working_dir: /tourist
        volumes:
          - ./docker/data/mysql:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=tourist
          - MYSQL_USER=root
          - MYSQL_PASSWORD=root
        ports:
          - "8082:3306"